INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT)
VALUES(1, 'USD', 'BRL', 5.44, 0);

INSERT INTO EXCHANGE_VALUE(ID, CURRENCY_FROM, CURRENCY_TO, CONVERSION_MULTIPLE, PORT)
VALUES(2, 'BRL', 'USD', 5.44, 0);